### ISSUE TITLE
TakeUntil the predicate returns `false` seems counterintuitive

### ISSUE THREAD

**Issue by scotteg** [infinum/iOS-Nuts-And-Bolts#18]
Your [implementation of `takeUntil`](https://github.com/infinum/iOS-Nuts-And-Bolts/blob/master/Sources/RxSwift/Observable/Observable%2BTakeUntil.swift) continues taking until the predicate returns `false`. This is the opposite of [RxSwift's implementation of `takeUntil(_:predicate:)`](https://github.com/ReactiveX/RxSwift/blob/6b2a406b928cc7970874dcaed0ab18e7265e41ef/RxSwift/Observables/TakeUntil.swift), that takes until the predicate is `true`.

**Comment by fgulan** [comment]
Thanks for the report!

Totally agree with you and we will remove this extension since it is not necessary anymore because RxSwift now has that operator. We've implemented this one a few years ago when RxSwift didn't have support for takeUntil with predicate.

**Comment by goranbrl** [comment]
Removed in the latest [approved PR](https://github.com/infinum/iOS-Nuts-And-Bolts/pull/19), thanks @scotteg for reporting 🙂
